### ISSUE TITLE
Visualization of split CDS in proksee.ca and multiple contigs

### ISSUE THREAD

**Issue by glucksfall** [proksee-project/proksee-cmd#84]
Hello,

I just found the project and I think it is amazing. I gave it a try using the Synechocystis sp. PCC 6803 genome (NC_000911, https://www.ncbi.nlm.nih.gov/nuccore/NC_000911). However, one issues is present:

- Some genes are not shown (e.g. SGL_RS01875). The gene and others are split: join(3573271..3573470,1..772)
~- The genome contains 5 contigs, but only the first is shown.~
- update: I tried the genbank file, and the 5 contigs are shown concatenate into one.

Best,

**Comment by ericenns** [comment]
Hi @glucksfall, this repo is for the assembly and evaluation tool used by proksee.ca, if you have an issue with proksee.ca I would either email `info@proksee.ca` or possibly open an issue on the `cgview-js` repo (https://github.com/stothard-group/cgview-js)
